### ISSUE TITLE
Game starts up with a ridiculously small window

### ISSUE THREAD

**Issue by silver-volt4** [Davoleo/Map-of-Zodiac#2]
Not sure if this is intentional. This is how the game starts up:
![Snímek z 2020-01-12 09-21-24](https://user-images.githubusercontent.com/35656715/72216107-f12f8080-351c-11ea-903a-4e3b53df82c2.png)
(This is absolutely Linux, not Mac OS. I have a skin.)

The game can be resized just fine, however I suggest it would be better if it started with a bigger window.

**Comment by Klazkin** [comment]
This is not a Linux specific issue, similar behavior occurs on windows too.
This happens because the game runs natively at resolution 320x180 and thus boots into it by default, I am well aware of it, I'll look into how to fix it.

That distro looks hella clean
